[phases.setup]
nixPkgs = ["(python311.withPackages (ps: with ps; [ pip ]))", "gcc"]
aptPkgs = ["chromium", "chromium-chromedriver", "libmariadb-dev", "libpq-dev"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
# We call gunicorn as a module here to avoid the 'command not found' error
cmd = "python3 manage.py collectstatic --noinput && python3 -m gunicorn backend.wsgi"