[phases.setup]
nixPkgs = ["python311", "gcc"]
aptPkgs = ["google-chrome-stable", "chromium-chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py collectstatic --noinput && gunicorn backend.wsgi"