[phases.setup]
nixPkgs = ["(python311.withPackages (ps: with ps; [ pip ]))", "gcc"]
aptPkgs = ["chromium", "chromium-chromedriver", "libmariadb-dev", "libpq-dev", "libnss3", "libatk1.0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libgtk-3-0", "libgbm1", "libasound2"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
# We call gunicorn as a module here to avoid the 'command not found' error
cmd = "python3 manage.py collectstatic --noinput && python3 -m gunicorn backend.wsgi"