# Generated by Django 5.2.12 on 2026-04-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_read_manga', 'Can read manga'), ('can_download_manga', 'Can download manga'), ('can_manage_users', 'Can manage users'), ('can_access_admin_panel', 'Can access admin panel')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
