# Generated by Django 5.2.12 on 2026-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_last_read_at_customuser_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_read_count',
            field=models.IntegerField(default=0),
        ),
    ]
