# Generated by Django 5.2.12 on 2026-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_total_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_streak_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reading_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reading_streak',
            field=models.IntegerField(default=0),
        ),
    ]
